### ISSUE TITLE
Gallery pages - Follow Vuetify Recommendations

### ISSUE THREAD

**Issue by novellac** [FrontEndFoxes/website#68]
**Issue**
When on a gallery page, Vuetify gives the warning that  `'justify-center' is deprecated, use 'class="justify-center"' instead`

**Impact**
There seems to be no impact to the user yet.

**Possible Fix**
Use class `justify-center`

**Comment by ratracegrad** [comment]
Submitted a PR for this issue. Went through and updated all occurances of justify-center with class="justify-center"

**Comment by novellac** [comment]
@MicheleCynowicz @ratracegrad Is this PR no longer open? I can't seem to find it in open or closed PRs.

**Comment by ratracegrad** [comment]
I deleted my fork to prepare for hactoberfest. I am working with Ania in Japan to help her submit a PR to upgrade to Vuetify 2 and handle all the changes needed as a result. For now close this PR and you will see a PR from Ania to handle this.
