### ISSUE TITLE
Fix - Correct repo author in package.json

### ISSUE THREAD

**Issue by novellac** [FrontEndFoxes/website#69]
**Issue**
Repo author in package.json is set to NT personal address

**Impact**
No impact to most users. May impact those who try to find the organization using this info.

**Fix**
Amend package.json with correct Vue Vixens author and name

**Bonus!**
To properly attribute work on the website, we could add a thanks section to the ~~About~~ Credits page.

**Comment by ratracegrad** [comment]
I submitted a PR to close this issue.
