### ISSUE TITLE
Enable localizations for the registration form

### ISSUE THREAD

**Issue by jlooper** [FrontEndFoxes/website#70]
We have supported localizations in the past, and the framework is still in place to allow for Spanish translations, for example. We pulled them out because they're very hard to maintain. However, we need to make our registration form localizable to support our Japanese chapter. I'd like to open a challenge: get our form localized and managed via Storyblok. What's the cleanest, easiest way to do this? 

Example: https://www.vuevixens.org/form/devreach2019. If this form is reached on the path https://www.vuevixens.org/es/form/devreach2019 the form should appear in Spanish. A change to Storyblok will also be necessary to enable the proper localized link

**Comment by alexandriaroberts** [comment]
I would like to do this!! Has this been assigned @novellac and @jlooper ?

**Comment by novellac** [comment]
Hi @alexandriaroberts it hasn't been assigned. I can assign it to you if you like!

**Comment by alexandriaroberts** [comment]
Yes, please!! I would like to work on this. Thank you @novellac !!

**Comment by alexandriaroberts** [comment]
Thank you! I am working on it now.
