### ISSUE TITLE
Create an Issue Template

### ISSUE THREAD

**Issue by novellac** [FrontEndFoxes/website#74]
**Feature request**
Let's create an issue template that people can use to make suggestions, report bugs, etc. Here is some preliminary reading to get us started:

https://help.github.com/en/articles/creating-issue-templates-for-your-repository

**Comment by nimitbhargava** [comment]
@novellac Can I take up this issue?

**Comment by sohaibalam67** [comment]
Hey! Can you assign this to me?

**Comment by novellac** [comment]
Sure @nimitbhargava I'll assign you. Please keep in touch and if you have questions, ask early and often! :)

**Comment by nimitbhargava** [comment]
I created #79 
I have used sample text, please let me know if you want to add something specific to the project.
