### ISSUE TITLE
Update Vuetify

### ISSUE THREAD

**Issue by novellac** [FrontEndFoxes/website#75]
**Task**
Update Vuetify and resolve any conflicts that arise.

**Comment by Ania-chan** [comment]
Hi! Can I try doing this issue? 🙏

**Comment by novellac** [comment]
> Hi! Can I try doing this issue? pray

Hi @Ania-chan You are welcome to give it a try! Please ask questions here if you run into any issues, and we will do our best to help!

**Comment by Ania-chan** [comment]
Thanks so much! I'll ask on Slack if I encounter any blockers :)

**Comment by nimitbhargava** [comment]
@novellac I would like to try it out. 
@Ania-chan if for some reason you'd like to pass I would want to take it up willingly. :D

**Comment by Ania-chan** [comment]
@nimitbhargava If for some reason I decide not to do this issue I'll let you know. But for the moment I'd really like top do it on my own.

**Comment by ratracegrad** [comment]
@Ania-chan Konnichiwa. Watashi wa Jennifer Bland desu. Watashi wa Nara ni sunde imashita. Nanika tetsudaimashou ka. I went through and upgraded to Vuetify 2 and fixed all the errors and incompatibilities. If you need help please reach out and we can pair program and work on it together. If you have it fixed already then great and thank you for the chance to try and speak Japanese again! Domo arigato.

**Comment by jlooper** [comment]
I believe we're good now!
